akorn_search/apps/accounts/urls.py
from django.conf.urls import patterns, url

from apps.accounts.views import RegisterView

urlpatterns = patterns('',
    url(r'^register/', RegisterView.as_view(), name='register'),
)

akorn_search/apps/search/templatetags/urls.py
from django.template import Library
from django.utils.safestring import mark_safe
import urlparse

register = Library()

@register.filter
def domain(value):
  url_parsed = urlparse.urlparse(value)
  return mark_safe(url_parsed.netloc)

@register.filter
def scraped_location(doc):
  if 'source_url' in doc:
    return doc['source_url']
  elif 'source_urls' in doc:
    return doc['source_urls'][len(doc['source_urls'])-1]
  else:
    return None

akorn_search/apps/search/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^search/$', views.HomeView.as_view(), name='home'),
    url(r'^doc/(?P<id>[A-Za-z0-9]+)$', views.DocView.as_view(), name='doc'),
    url(r'^journal/(?P<id>.*)$', views.JournalView.as_view(), name='journal'),
)

akorn_search/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# TODO Should be handled by a catch-all, but can't because of search app
urlpatterns = patterns('django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^volunteer/$', 'flatpage', {'url': '/volunteer/'}, name='volunteer'),
    url(r'^$', 'flatpage', {'url': '/'}, name='main'),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^sim/', include('apps.simulator.urls', namespace='sim')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name="auth_logout"),
    url(r'^login/$', 'django.contrib.auth.views.login',
        name="auth_login"),
    url(r'', include('apps.search.urls', namespace='search')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^'+settings.STATIC_URL[1:]+'(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
    )

akorn_search/apps/search/models.py
from django.db import models

from django_extensions.db.fields.json import JSONField

from apps.accounts.models import AkornUser

class Search(models.Model):
    query = JSONField()
    last_visited = models.DateTimeField()
    user = models.ForeignKey(AkornUser, blank=True, null=True)

akorn_search/apps/search/views.py
import datetime
import couchdb

from django.http import Http404
from django.views.generic import TemplateView

from couch import db_store, db_journals

import apps.api.views
import apps.panes.models

class HomeView(TemplateView):
    template_name = 'search/home.html'


class DocView(TemplateView):
    template_name = "search/doc.html"

    def get_context_data(self, **kwargs):
        doc_id = self.kwargs['id']
        doc = db_store[doc_id]
        doc['docid'] = doc_id

        try:
            date_published = datetime.datetime.fromtimestamp(doc['date_published'])
        except:
            date_published = None
        
        try:
            date_scraped = datetime.datetime.fromtimestamp(doc['date_scraped'])
        except:
            date_scraped = None
        
        try:
            if doc['date_revised'] != doc['date_published']:
                date_revised = datetime.datetime.fromtimestamp(doc['date_revised'])
            else:
                date_revised = None
        except:
            date_revised = None

        date_warning = False
        if date_scraped is not None and date_published is not None:
            if date_scraped.date() > date_published.date() + datetime.timedelta(days=7):
                date_warning = True

        # Process the IDs to make them usable in URLS
        # TODO Make this more robust, but retain slash to underscore behaviour
        #pane_doc_ids = {k: v.replace('/', '_') for k, v in doc['ids'].iteritems()}

        #panes = apps.panes.models.Pane.objects.all()

        valid_panes = []

        #for p in panes:
        #    try:
        #        valid_panes.append({'name': p.name,\
        #            'url': p.url.format(**pane_doc_ids)})
        #    except KeyError:
        #        print "Pane not valid for article"

        return {'doc': doc,
                'date_published': date_published,
                'date_scraped': date_scraped,
                'date_warning': date_warning,
                'date_revised': date_revised,
                'panes': valid_panes}


class JournalView(TemplateView):
    template_name = "search/journal.html"

    def get_context_data(self, **kwargs):
        # Get their last visit
        last_visit = self.request.session.get('last_visit')
        journal_id = self.kwargs['id']
        if not journal_id:
            # TODO Should be bad request?
            raise Http404
        try:
            journal = db_journals[journal_id]
        except couchdb.ResourceNotFound:
            # Throw a 404 if couchdb doc does not exist
            raise Http404
        return {'last_visit': last_visit, 'journal': journal}

akorn_search/apps/search/templates/search/article_list.html
{% for doc in docs %}
<li id="{{ doc.docid }}" itemscope itemtype="http://schema.org/Article">
<h3 itemprop="name">
    <a href="{% url 'search:doc' doc.docid %}" title="{{ doc.title }}">{{ doc.title|truncatewords:12 }}</a>
</h3>
<p class="meta">
    <meta itemprop="datePublished" content="{{ doc.date|date:"c" }}">
    {% if doc.author_names %}
    <span class="authors">
    {% with author_count=doc.author_names|length %}
    {% if author_count > 3 %}
        {{ doc.author_names|slice:"2"|join:", " }} &hellip;
        {{ doc.author_names|last }}
    {% else %}
        {{ doc.author_names|join:", " }}
    {% endif %}
    {% endwith %}</span>
    {% endif %}
    {% if doc.journal %}
        — <span class="journal"><a href='{{ doc.source_urls.0 }}'>{{ doc.journal }}</a></span>
    {% endif %}
    </p>
</li>
{% endfor %}

akorn_search/apps/search/templates/search/doc.html
{% extends 'page.html' %}
{% load urls %}

{% block canonical %}<link rel="canonical" href="{% url 'search:doc' doc.docid %}">{% endblock %}

{% block og_meta %}
<meta property="og:title" content="{{ doc.title }}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{ doc.abstract }}" />
<meta property="og:image" content="{{ STATIC_URL}}search/img/article.jpg" />
<meta property="og:url" content="{% url 'search:doc' doc.docid %}" />
<meta property="og:site_name" content="Akorn.org" />
<!-- Facebook ID of Craig Loftus -->
<meta property="fb:admins" content="506422046" />
{% endblock %}

{% block container %}
<div id="fb-root"></div>

<div id="content" class="container-fluid">

<div itemscope itemtype="http://schema.org/CreativeWork">
<div class="row-fluid">
    <div class='span8 box_title'>
        <h1 itemprop="name"><a href='{{ doc.source_urls.0 }}'>{{ doc.title }}</a></h1>
    </div>
</div>

{% if date_warning %}
<div class='row-fluid'>
    <div class='span8' style='background-color:#FFC;text-style:italic;padding:5px;'>
        This article was originally published on <strong>{{ date_published|date:"D j F Y" }}</strong> although we only indexed it on <strong>{{ date_scraped|date:"D j F Y" }}</strong>
    </div>
</div>
{% endif %}

<div class='row-fluid'>
    <div class='span8 box_date'>
      {% if date_published %}
        published on <strong>{{ date_published|date:"D j F Y" }}</strong> in <strong><a href="{% url 'search:journal' doc.journal_id %}">{{ doc.journal }}</a></strong>
      {% else %}
        published on <strong>{{ date_published }}</strong> in <strong><a href="{% url 'search:journal' doc.journal_id %}">{{ doc.journal }}</a></strong>
      {% endif %}
      {% if date_revised %}
        and revised on <strong>{{ date_revised|date:"D j F Y" }}</strong>.
      {% endif %}
    </div>
</div>

<div class='row-fluid'>
    <div class='span8 box_authors'>
        {% for author in doc.author_names %}
          <div class='author_name {% if forloop.counter > 10 %}author_name_hidden{% endif %}'>
          {% if author.surname %}
            {{ author.forename }} {{ author.surname }}{% if not forloop.last %},{% endif %}
          {% else %}
           {{ author }}{% if not forloop.last %},{% endif %}
          {% endif %}
          </div>
          {% if forloop.counter == 11 %}
            <div class='author_name author_name_show_link'><a onclick="$('.author_name_hidden').show();$(this).hide();">see all {{ doc.author_names|length }}</a></div>
          {% endif %}
        {% endfor %}
    </div>
</div>

<div class='row-fluid'>
    <div class='span6 box_abstract' itemprop="description">
      {% if doc.abstract %}
      <div class='abstract'>
        {{ doc.abstract }}
      </div>
      {% endif %}
    </div>

    <div class='span4 box_info'>
      {% if doc.publisher %}<strong>published by</strong> {{ doc.publisher }}<br/>{% endif %}
      {% if doc.doi %}<strong>doi</strong> <a href='http://dx.doi.org/{{ doc.doi }}'>{{ doc.doi }}</a><br/>{% endif %}
      {% if doc.arxiv %}<strong>arxiv</strong> <a href='http://arxiv.org/abs/'>{{ doc.arxiv }}</a><br/>{% endif %}
    </div>

    <div class='span4 box_share'>
      <div class="share-button g-plusone"></div>

      <div class="share-button tweet">
        <a href="https://twitter.com/share" class="twitter-share-button" data-dnt="true">Tweet</a>
      </div>

      <div class="share-button fb-like" data-send="false" data-layout="button_count" data-width="90" data-show-faces="false" data-action="like" data-colorscheme="light"></div>
    </div>
</div>

</div>

<div class='row-fluid'>
    <div id="panes" class="span6">
        {% for p in panes %}
            <div class="accordion-group" data-pane-url="{{ p.url }}">
                <div class="accordion-heading">
                    <a class="accordion-toggle"
                        href="#collapse{{ forloop.counter }}">
                        {{ p.name }}
                        <i class="icon-chevron-right"></i>
                </a>
                </div>

                <div id="collapse{{ forloop.counter }}"
                    style="display:none">
                    <div class="accordion-inner">
                        Loading&hellip;
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/main.js"></script>

<script type="text/javascript">
// When the document has loaded start the show
$(document).ready(function(e) {

        $('#panes').on('click', ".accordion-heading", function(e) {
            var cur = $(e.currentTarget);
            // Set the little arrow to the right state
            cur.find("i")
                .toggleClass("icon-chevron-down", "icon-chevron-right");
            // Open the pane and load the content
            cur.next().toggle('slow', function() {
                if ($(this).is(":visible")) {
                    var par = cur.parent();
                    akorn.load_pane(par.data('pane-url'), par);
                }
            });
            return false;
        });
    });
</script>

<script type="text/javascript">
// Google plus button
window.___gcfg = {lang: 'en-GB'};
(function() {
    var po = document.createElement('script'); po.type =
    'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(po, s);
    })();

// Tweet link

// Facebook plugin
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
{% endblock %}

akorn_search/apps/search/templates/search/home.html
{% extends 'page.html' %}
{% load search_filters %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/main.js"></script>
<script type="text/javascript">
{% if last_visit %}
// TODO There is probably a better way to do this
akorn.last_visit = "{{ last_visit|date:"c" }}";
{% endif %}
// When the document has loaded start the show
$(document).ready(akorn.init);
</script>
{% endblock %}

{% block container %}
<div class="row-fluid">
    <div class="span9 search" id="search_bar">
        <form action="/search/" method="get" class="form-inline">
            <input type="hidden" name="q" placeholder="Search for journals and keywords…" id="search">
            <button id="save_search" class="btn btn-primary" title="Save this search">Save search</button>
        </form>
    </div>
</div>

<div id="main_row" class="row">
    <div class="span3">
        <ul id="saved_searches">
        </ul>
        {% if not request.user.is_authenticated %}
        <a style='display:block;padding:0.5em;margin:0.5em;margin-left:25px;width:10em;' href='{% url "accounts:register" %}'>Sign up to keep your saved searches</a>
        {% endif %} 
    </div>

    <div id="articles_container" class="span8">
        <div id='intro'>
          <img src='/static/guide.png' alt='guide'/>
          <!--<p>To create a search, start by typing in names of journals or keywords in the box above and press 'enter' to finish.</p>
          <p>Names of journals will autocomplete and then you can select the journal you want.</p>
          <p>For keywords, just type a series of keywords that you want to be ANDed together and press 'enter'.</p>
          <p>'Save search' will keep the search as a convenient link in the left hand column.</p>-->
        </div>
        <ul id="articles">
        </ul>
        <div id="msg" style="display: none">
        </div>
    </div>
</div>
{% endblock %}

akorn_search/apps/search/templates/search/journal.html
{% extends 'page.html' %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/main.js"></script>
<script type="text/javascript">
// When the document has loaded start the show
$(document).ready(function() {
        var ak = akorn;
        var query = [{'type': 'journal', 'id': '{{ journal.id }}'}];
        ak.query = query;
        ak.articles_container = $('#articles');
        ak.get_articles(query, true);
        $(window).scroll(ak.throttle(function() {
            ak.check_position();
        }, 250));
    });
</script>
{% endblock %}

{% block container %}
<div id="content" class="container-fluid">

<div class="row-fluid">
    <div class='span12 box_title'>
        <h1>{{ journal.name }}</h1>
    </div>
</div>

<div class="row-fluid">
    <div class='span8 box_date'>
      Also known as: {% for alias in journal.aliases %}{{ alias }}{% if not forloop.last %}, {% endif %}{% endfor %}
    </div>
</div>

<div class="row-fluid">
    <div class=''></div>
    <div class='span8 offset3 box_articles'>
        <ul id='articles'>
        </ul>
    </div>
</div>

</div>
{% endblock %}

akorn_search/apps/search/templates/search/results.html
{% extends "page.html" %}

{% block pagetitle %}
results for {{ search_request }}
{% endblock %}

{% block content %}
<div class='grid_12 alpha omega'>
  <h1>Results for '{{ search_request }}'</h1>
</div>
<div class='grid_8 alpha'>
  {% for doc in docs %}
        <div class="row stream-item">
            {% if doc.uri %}
              <p><a href="{{ doc.uri }}">{{ doc.title }}</a></p>
            {% else %}
              <p>{{ doc.title }}</p>
            {% endif %}
            <p><small>
                {% for author in doc.author_names %}
                  {% if author.surname %}
                    {{ author.forename }} {{ author.surname }}
                  {% else %}
                    {{ author }}
                  {% endif %}
                  {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </small></p>
            {% if doc.ids.doi %}
              {{ doc.ids.doi }} - 
            {% endif %}
            <a href="{% url 'search:doc' id=doc.docid %}">{{ doc.docid }}</a>
            - from {{ doc.api.name }}
        </div>
  {% endfor %}
</div>
<div class='grid_4 omega'>
  Right bar.
</div>
<!--<div class="tabbable">
    <ul class="nav nav-tabs">
        {% for api in api_results %}
        <li {% if forloop.first %}class="active"{% endif %}><a href="#{{ api.id }}" data-toggle="tab">{{ api.name }}</a></li>
        {% endfor %}
    </ul>
    <div class="tab-content">
        {% for api in api_results %}
        <div class="tab-pane{% if forloop.first %} active{% endif %}" id="{{ api.id }}">
          {% for result in api.results %}
            <div class="row stream-item">
                {% if result.uri %}
                <p><a href="{{ result.uri }}">{{ result.title }}</a></p>
                {% else %}
                <p>{{ result.title }}</p>
                {% endif %}
                <p><small>
                    {% for author in result.authors %}
                    {% if author.surname %}
                    {{ author.forename }} {{ author.surname }}
                    {% else %}
                    {{ author }}
                    {% endif %}
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </small></p>
                {% if result.doi %}
                <small>doi:<a href="http://dx.doi.org/{{ result.doi }}">{{result.doi}}</a></small>
                {% endif %}
            </div>
          {% endfor %}
      </div>
      {% endfor %}
</div>
</div>-->
{% endblock %}