akorn_search/apps/simulator/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^$', views.SimulatorView.as_view(), name='simulator'),
)

akorn_search/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# TODO Should be handled by a catch-all, but can't because of search app
urlpatterns = patterns('django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^volunteer/$', 'flatpage', {'url': '/volunteer/'}, name='volunteer'),
    url(r'^$', 'flatpage', {'url': '/'}, name='main'),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^sim/', include('apps.simulator.urls', namespace='sim')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'},
        name="auth_logout"),
    url(r'^login/$', 'django.contrib.auth.views.login',
        name="auth_login"),
    url(r'', include('apps.search.urls', namespace='search')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^'+settings.STATIC_URL[1:]+'(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
    )

akorn_search/apps/simulator/models.py
from django.db import models

# Create your models here.

akorn_search/apps/simulator/forms.py
from django import forms

example_config = """{
    \"title\": [
        {\"type\": \"metaTag\", \"value\": \"dc.title\"}
        ],
    \"date_published\": [
        {\"type\": \"metaTag\", \"value\": \"dc.date\"}
        ],
    \"author_names\": [
        {\"type\": \"metaList\", \"value\": \"dc.contributor\"}
        ],
    \"journal\": [
        {\"type\": \"metaTag\", \"value\": \"citation_journal_title\"}
        ],
    \"abstract\": [
        {\"type\": \"css\", \"value\": \"div.section p\", \"single\": true}
        ],
    \"publisher\": [
        {\"type\": \"metaTag\", \"value\": \"dc.publisher\"}
        ],
    \"doi\": [
        {\"type\": \"metaTag\", \"value\": \"citation_doi\"}
        ]
}"""

class SimulatorForm(forms.Form):
    scraper_config = forms.CharField(widget=forms.Textarea, initial=example_config)
    feed_url = forms.URLField(initial="http://", label="Feed URL")
    article_tag = forms.CharField(initial="link", help_text="The tag that contains the article URL in each feed item")
    article_url = forms.CharField(widget=forms.HiddenInput, required=False)

akorn_search/apps/simulator/views.py
import feedparser
import functools
import hashlib
import lxml
import random

from django.core.cache import cache
from django.core.mail import mail_managers
from django.http import HttpResponse
from django.views.generic import FormView
from django.template.loader import render_to_string
from django import forms

from .forms import SimulatorForm

import akorn.scrapers.base as base
import akorn.scrapers.utils as utils


class SimulatedConfig(base.Config):
    def __init__(self, config_str):
        parsed = self.parse_config(config_str)
        compiled_config = self.compile_config(parsed)
        # Place the config where it needs to be
        self.config = compiled_config


class SimulatedScraper(base.BaseScraper):
    def __init__(self, config_str):
        """
        Overload BaseScraper.__init__, to load config from param not file
        """
        self.config = SimulatedConfig(config_str)

    def fetch_url(self, url):
        # Check cache first
        cache_key = hashlib.sha224(url).hexdigest()
        content = cache.get(cache_key)
        if not content:
            content = super(SimulatedScraper, self).fetch_url(url)
            # Cache for 10 minutes
            cache.set(cache_key, content, 10*60)
        urls, page, page_url = content
        return urls, page, page_url

    def valid(self, data):
        missing = []
        # Curry check_value with container for missing properties
        curried_check = functools.partial(self.check_value, missing=missing)
        # Walk over the acquired data to check a value is set for each property
        utils.walk_and_apply(data, curried_check)
        # Set the list of missing properties as instance variable
        self.missing = missing
        return missing


class SimulatorView(FormView):
    template_name = 'simulator/simulator.html'
    form_class = SimulatorForm

    def scrape_feed(self, feed_url, url_key='link'):
        """
        Return list of article URLS to scrape
        """

        cache_key = hashlib.sha224(feed_url+url_key).hexdigest()
        # Look in the cache first
        article_urls = cache.get(cache_key)
        if article_urls:
            return article_urls

        items = feedparser.parse(feed_url).get('items')
        if not items:
            raise Exception("Failed to scrape feed")

        article_urls = [item.get(url_key) for item in items if url_key in item]

        if not article_urls:
            raise Exception("Failed to find URLs in feed. Try one of: {}.".format(', '.join(item.keys())))

        # Cache for 10 minutes
        cache.set(cache_key, article_urls, 10*60)

        return article_urls

    def scrape_article(self, url, scraper):
        article = {}
        try:
            # Record the URL we're attempting to scrape
            article['url'] = url
            # Use the supplied config to scrape the given url
            article['scraped'], scraper = self.simulate_scrape(url, scraper)
            article['out_missing'] = scraper.missing
            article['config'] = scraper.config
        except Exception as e:
            # Catch other errors and pass to context
            article['out_error'] = str(e)
        return article

    def simulate_scrape(self, url, scraper):
        """
        Return dict of scraped article
        """
        # Scrape the given url
        return scraper.scrape_article(url), scraper

    def email_config(self, form):
        # Then email the config and feed definition to Managers
        mail_managers('Scraper request',
            render_to_string('simulator/email.txt',
                {'data': form.cleaned_data, 'user': self.request.user}))

    def run_config(self, form, context):
        # Add the supplied form into the context
        try:
            # Find the form inputs
            feed_url = form.cleaned_data['feed_url']
            url_key = form.cleaned_data['article_tag']
            config = form.cleaned_data['scraper_config']
            article_url = form.cleaned_data['article_url']
            # If specific articles are requested, then ignore the feed
            if article_url:
                articles = [article_url]
                # Reset the article_url value
                context['form'].data['article_url'] = ''
            else:
                # Parse the feed and find the article urls
                articles = self.scrape_feed(feed_url, url_key)
            # Instantiate the scraper with the supplied configuration
            scraper = SimulatedScraper(config)
            # Grab at most 2 articles
            sample = 2
            if len(articles) > sample:
                articles = random.sample(articles, sample)
            # Try to scrape the selected articles
            context['articles'] = [self.scrape_article(url, scraper) for url in articles]
        except KeyError as e:
            context['error'] = 'All fields are required'
        except Exception as e:
            context['error'] = str(e)
        return context

    def form_valid(self, form):
        """
        Return template rendered with scraped content or error
        """
        context = {'form': form}

        # If the user pressed the Save button, rather than run
        if self.request.POST.get('save'):
            self.email_config(form)
        else:
            # Copy the data so that it is mutable
            form.data = self.request.POST.copy()
            # Run the configuration
            context = self.run_config(form, context)

        # Render the original template with the new context
        return self.render_to_response(context)

akorn_search/apps/simulator/templates/simulator/simulator.html
{% extends 'page.html' %}
{% load i18n assets print_results %}

{% block style %}
    {{ block.super }}
    {% assets "sim_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $('.retry-article').on('click', function(e) {
            var url = $(e.currentTarget).parent().data('url');
            $('#id_article_url').val(url);
            $('#config_form').submit();
        });
    </script>
{% endblock %}

{% block content %}

{% if error %}
    <div id="error" class="alert alert-error">
        {{ error }}
    </div>
{% endif %}

<div id="config" class="span5">
    <h2>{% trans "Config" %}</h2>
    {{ form.errors }}
    {% if config.missing %}
            <div class="alert alert-error">
                <h4>{% trans "Missing:" %}</h4>
                <ul>{{ config.missing|unordered_list }}</ul>
            </div>
    {% endif %}

    {% if config.not_allowed %}
            <div class="alert alert-error">
                <h4>{% trans "Invalid properties:" %}</h4>
                <ul>{{ config.not_allowed|unordered_list }}</ul>
            </div>
    {% endif %}

    {% if config.unused %}
            <div class="alert alert-info">
                <h4>{% trans "Consider adding:" %}</h4>
                <ul>{{ config.unused|unordered_list }}</ul>
            </div>
    {% endif %}
    <form name="config" action="." method="post" id="config_form">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
        <input class="btn-primary btn-large" type="submit" value="{% trans "Run" %}" />
        </p>

        {% if articles and not config.not_allowed and not config.missing and not form.errors and not out_missing %}
        <p>
        <input class="btn-primary btn-large" name="save" type="submit" value="{% trans "Submit" %}" />
        </p>
        {% endif %}
    </form>
</div>
<div id="preview" class="span5">
    <h2>{% trans "Preview" %}</h2>

    {% if articles %}

    <p>Tried {{ articles|length }} random articles from the feed:</p>
    <ul>
    {% for a in articles %}
    <li data-url="{{ a.url }}">{{ a.url }} <i class="icon-refresh retry-article"></i></li>
    {% endfor %}
    </ul>

    {% for a in articles %}
        {% if a.out_error %}
            <div class="alert alert-error">
                <h4>{% trans "Error" %}</h4>
            <p>{{ a.out_error }}</p>
            </div>
        {% else %}
            {% if a.out_missing %}
                <div class="alert alert-error">
                    <h4>{% trans "Missing properties" %}</h4>
                    <p>{{ a.out_missing|join:", " }}</p>
                </div>
            {% endif %}
            {{ a.scraped|to_dl }}
        {% endif %}
    {% endfor %}

    {% endif %}
</div>
{% endblock %}